### ISSUE TITLE
请教个本地视频直播问题

### ISSUE THREAD

**Issue by dalehqb** [AnyRTC/anyRTMPC-HybridEngine-iOS#4]
有个DLNA 的项目，想把相册本地视频做 DLNA 推送；
个人想的是做一个 rtmp 地址推送，rtmp 服务器在手机端实现，通过 DLNA 协议推送到其他 DMR，这样是否可行？你这个项目有哪些可以借鉴？谢谢

**Comment by BoYuanZjq** [comment]
你好，这个不在我们的业务范围内
