### ISSUE TITLE
一打开说服务错误

### ISSUE THREAD

**Issue by AdwardWong** [AnyRTC/anyRTMPC-HybridEngine-iOS#7]
一打开说服务错误

**Comment by BoYuanZjq** [comment]
需要先配置开发者信息才能运行项目，需要去我们官网注册开发者，并创建应用

--------------原始邮件--------------
发件人："AdwardWang "<notifications@github.com>;
发送时间：2018年11月13日(星期二) 晚上6:07
收件人："anyRTC/anyRTC-RTMPC-iOS" <anyRTC-RTMPC-iOS@noreply.github.com>;
抄送："Subscribed "<subscribed@noreply.github.com>;
主题：[anyRTC/anyRTC-RTMPC-iOS] 一打开说服务错误 (#7)
-----------------------------------

 
一打开说服务错误
